<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 08 Jun 2022 19:22:31 +0000
 */

$conf['title'] = 'Tabulify - Growing data proficiency of the world';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useheading'] = '1';
$conf['indexdelay'] = 0;
$conf['sitemap'] = 5;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['combo']['prismTheme'] = 'prism';
$conf['plugin']['combo']['mandatoryQualityRules'] = 'internal_backlinks_min,internal_links_min,words_min';
$conf['plugin']['combo']['primaryColor'] = '#326e32';
$conf['plugin']['combo']['privateRailbar'] = 1;
$conf['plugin']['googleanalytics']['GTAGID'] = 'G-4XWKFHYS5D';
$conf['plugin']['googletagmanager']['GTMID'] = 'GTM-MD83VQ8';
$conf['disableactions'] = 'register';
$conf['lang'] = 'en';
