<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 08 Jun 2022 19:22:31 +0000
 */

$conf['title'] = 'Tabulify';
$conf['license'] = 'cc-by-sa';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['renderer_xhtml'] = 'combo_renderer';
$conf['plugin']['combo']['mandatoryQualityRules'] = 'internal_backlinks_min,internal_links_min,words_min';
$conf['plugin']['combo']['outlineNumberingEnable'] = 1;
$conf['tpl']['strap']['footerSlotPageName'] = 'slot_footer';
$conf['tpl']['strap']['headerSlotPageName'] = 'slot_header';
$conf['tpl']['strap']['sidekickSlotPageName'] = 'slot_sidekick';
