<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 08 Jun 2022 19:22:31 +0000
 */

$conf['title'] = 'Tabulify';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['combo']['mandatoryQualityRules'] = 'internal_backlinks_min,internal_links_min,words_min';
$conf['plugin']['combo']['outlineNumberingEnable'] = 1;
$conf['plugin']['combo']['primaryColor'] = '#326e32`;
